/**
 * Routes for Activate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { activateBehaviourBaseline } from "../handlers/activate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function activateRoutes(fastify: FastifyInstance) {
  // POST /v1/baselines/{baselineId}/activate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/baselines/:baselineId/activate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { baselineId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBaselinesDependenciesForRequest();
        await activateBehaviourBaseline(request, reply, deps);
      });
    }
  );


}
