/**
 * RefreshKeyRiskIndicator handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { refreshKeyRiskIndicator } from "@alertworth/api-server/domains/indicators/handlers";
import type { IndicatorsDDDDependencies } from "@alertworth/api-server/domains/indicators";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alertworth/tests/shared";
import { INDICATORS_USE_CASES } from "../__factories__/use-cases.js";

describe("RefreshKeyRiskIndicator", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IndicatorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IndicatorsDDDDependencies>(
      INDICATORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { kriId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRefreshKeyRiskIndicator, "execute").mockResolvedValue(useCaseResult);

    await refreshKeyRiskIndicator(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRefreshKeyRiskIndicator.execute).toHaveBeenCalledWith(expect.objectContaining({ kriId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
