/**
 * Handlers for Admit
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TriageDomainModule } from "../dependencies/triage-ddd.dependencies.js";
import type { AdmitAlertToQueueInput } from "@alertworth/services/triage";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/triage/queue/admit
 * Operation: admitAlertToQueue
 */
export async function admitAlertToQueue(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TriageDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AdmitAlertToQueueInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.admits.get.execute(input);
  return reply.code(201).send(result);
}


