/**
 * Handlers for Queue
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TriageDomainModule } from "../dependencies/triage-ddd.dependencies.js";
import type { ListTriageQueueInput } from "@alertworth/services/triage";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/triage/queue
 * Operation: listTriageQueue
 */
export async function listTriageQueue(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], shiftId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TriageDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTriageQueueInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.queues.list.execute(input);
  return reply.code(200).send(result);
}


