/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@alertworth/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildBaselinesDomainModule,
  buildControlsDomainModule,
  buildEventsDomainModule,
  buildIdentityDomainModule,
  buildIndicatorsDomainModule,
  buildInvestigationsDomainModule,
  buildReportingDomainModule,
  buildScoringDomainModule,
  buildTriageDomainModule,
} from "../domains/index.js";
import type {
  BaselinesDomainModule,
  ControlsDomainModule,
  EventsDomainModule,
  IdentityDomainModule,
  IndicatorsDomainModule,
  InvestigationsDomainModule,
  ReportingDomainModule,
  ScoringDomainModule,
  TriageDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private baselinesModule: BaselinesDomainModule | null = null;
  private controlsModule: ControlsDomainModule | null = null;
  private eventsModule: EventsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private indicatorsModule: IndicatorsDomainModule | null = null;
  private investigationsModule: InvestigationsDomainModule | null = null;
  private reportingModule: ReportingDomainModule | null = null;
  private scoringModule: ScoringDomainModule | null = null;
  private triageModule: TriageDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get baselines domain module
   */
  getBaselinesDependencies(): BaselinesDomainModule {
    if (!this.baselinesModule) {
      this.baselinesModule = buildBaselinesDomainModule(this.dynamoClient);
    }
    return this.baselinesModule;
  }

  /**
   * Get controls domain module
   */
  getControlsDependencies(): ControlsDomainModule {
    if (!this.controlsModule) {
      this.controlsModule = buildControlsDomainModule(this.dynamoClient);
    }
    return this.controlsModule;
  }

  /**
   * Get events domain module
   */
  getEventsDependencies(): EventsDomainModule {
    if (!this.eventsModule) {
      this.eventsModule = buildEventsDomainModule(this.dynamoClient);
    }
    return this.eventsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get indicators domain module
   */
  getIndicatorsDependencies(): IndicatorsDomainModule {
    if (!this.indicatorsModule) {
      this.indicatorsModule = buildIndicatorsDomainModule(this.dynamoClient);
    }
    return this.indicatorsModule;
  }

  /**
   * Get investigations domain module
   */
  getInvestigationsDependencies(): InvestigationsDomainModule {
    if (!this.investigationsModule) {
      this.investigationsModule = buildInvestigationsDomainModule(this.dynamoClient);
    }
    return this.investigationsModule;
  }

  /**
   * Get reporting domain module
   */
  getReportingDependencies(): ReportingDomainModule {
    if (!this.reportingModule) {
      this.reportingModule = buildReportingDomainModule(this.dynamoClient);
    }
    return this.reportingModule;
  }

  /**
   * Get scoring domain module
   */
  getScoringDependencies(): ScoringDomainModule {
    if (!this.scoringModule) {
      this.scoringModule = buildScoringDomainModule(this.dynamoClient);
    }
    return this.scoringModule;
  }

  /**
   * Get triage domain module
   */
  getTriageDependencies(): TriageDomainModule {
    if (!this.triageModule) {
      this.triageModule = buildTriageDomainModule(this.dynamoClient);
    }
    return this.triageModule;
  }

  clearBaselinesDependencies(): void { this.baselinesModule = null; }
  clearControlsDependencies(): void { this.controlsModule = null; }
  clearEventsDependencies(): void { this.eventsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearIndicatorsDependencies(): void { this.indicatorsModule = null; }
  clearInvestigationsDependencies(): void { this.investigationsModule = null; }
  clearReportingDependencies(): void { this.reportingModule = null; }
  clearScoringDependencies(): void { this.scoringModule = null; }
  clearTriageDependencies(): void { this.triageModule = null; }

  getBaselinesDependenciesForRequest(): BaselinesDomainModule {
    return this.getBaselinesDependencies();
  }

  getControlsDependenciesForRequest(): ControlsDomainModule {
    return this.getControlsDependencies();
  }

  getEventsDependenciesForRequest(): EventsDomainModule {
    return this.getEventsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getIndicatorsDependenciesForRequest(): IndicatorsDomainModule {
    return this.getIndicatorsDependencies();
  }

  getInvestigationsDependenciesForRequest(): InvestigationsDomainModule {
    return this.getInvestigationsDependencies();
  }

  getReportingDependenciesForRequest(): ReportingDomainModule {
    return this.getReportingDependencies();
  }

  getScoringDependenciesForRequest(): ScoringDomainModule {
    return this.getScoringDependencies();
  }

  getTriageDependenciesForRequest(): TriageDomainModule {
    return this.getTriageDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.baselinesModule = null;
    this.controlsModule = null;
    this.eventsModule = null;
    this.identityModule = null;
    this.indicatorsModule = null;
    this.investigationsModule = null;
    this.reportingModule = null;
    this.scoringModule = null;
    this.triageModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
