/**
 * Handlers for CommitteePack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportingDomainModule } from "../dependencies/reporting-ddd.dependencies.js";
import type { AssembleCommitteePackInput } from "@alertworth/services/reporting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/committee-packs
 * Operation: assembleCommitteePack
 */
export async function assembleCommitteePack(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AssembleCommitteePackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.committeePacks.get.execute(input);
  return reply.code(201).send(result);
}


