/**
 * Handlers for CyberRiskAppetite
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportingDomainModule } from "../dependencies/reporting-ddd.dependencies.js";
import type { GetCyberRiskAppetiteInput, UpdateCyberRiskAppetiteInput } from "@alertworth/services/reporting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/cyber-risk-appetite
 * Operation: getCyberRiskAppetite
 */
export async function getCyberRiskAppetite(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCyberRiskAppetiteInput = {};
  const result = await deps.useCases.cyberRiskAppetites.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/cyber-risk-appetite
 * Operation: updateCyberRiskAppetite
 */
export async function updateCyberRiskAppetite(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateCyberRiskAppetiteInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.cyberRiskAppetites.update.execute(input);
  return reply.code(200).send(result);
}


