/**
 * Indicators Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const defineKeyRiskIndicator_Body = z
  .object({
    name: z.string(),
    threshold: z.number(),
    maxEvidenceAgeHours: z.number().int(),
    minCoverage: z.number().optional(),
    ownerId: z.string(),
  })
  .passthrough();
const refreshKeyRiskIndicator_Body = z
  .object({
    collectedAt: z.string().datetime({ offset: true }),
    coverage: z.number(),
    sourceRefs: z.array(z.string()).optional(),
    evidenceHash: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  defineKeyRiskIndicator_Body,
  refreshKeyRiskIndicator_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/kris',
    alias: 'listKeyRiskIndicators',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^kri_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string(),
                  threshold: z.number().optional(),
                  currentValue: z.number().optional(),
                  freshnessState: z.enum(['fresh', 'degrading', 'stale']),
                  evidenceCoverage: z.number().optional(),
                  maxEvidenceAgeHours: z.number().int().optional(),
                  minCoverage: z.number().optional(),
                  ownerId: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/kris',
    alias: 'defineKeyRiskIndicator',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: defineKeyRiskIndicator_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^kri_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            threshold: z.number().optional(),
            currentValue: z.number().optional(),
            freshnessState: z.enum(['fresh', 'degrading', 'stale']),
            evidenceCoverage: z.number().optional(),
            maxEvidenceAgeHours: z.number().int().optional(),
            minCoverage: z.number().optional(),
            ownerId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/kris/:kriId/refresh',
    alias: 'refreshKeyRiskIndicator',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: refreshKeyRiskIndicator_Body,
      },
      {
        name: 'kriId',
        type: 'Path',
        schema: z.string().regex(/^kri_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^kri_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            threshold: z.number().optional(),
            currentValue: z.number().optional(),
            freshnessState: z.enum(['fresh', 'degrading', 'stale']),
            evidenceCoverage: z.number().optional(),
            maxEvidenceAgeHours: z.number().int().optional(),
            minCoverage: z.number().optional(),
            ownerId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
