/**
 * Activate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Activate DTOs
 *
 * DDD: Application DTOs for Activate use cases.
 */

import type { ActivateBehaviourBaselineParams } from "@alertworth/core/baselines/types";

export type ActivateBehaviourBaselineInput = ActivateBehaviourBaselineParams;

export type ActivateBehaviourBaselineOutput = {};
