/**
 * Anomaly DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Anomaly DTOs
 *
 * DDD: Application DTOs for Anomaly use cases.
 */

import type { ListAnomalyDetectionsParams } from "@alertworth/core/baselines/types";

export type ListAnomalyDetectionsInput = ListAnomalyDetectionsParams;

export type ListAnomalyDetectionsOutput = {};
