/**
 * Baseline DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Baseline DTOs
 *
 * DDD: Application DTOs for Baseline use cases.
 */

import type { CreateBehaviourBaselineRequestInput, ListBehaviourBaselinesParams } from "@alertworth/core/baselines/types";

export type ListBehaviourBaselinesInput = ListBehaviourBaselinesParams;

export type CreateBehaviourBaselineInput = CreateBehaviourBaselineRequestInput;

export type ListBehaviourBaselinesOutput = {};

export type CreateBehaviourBaselineOutput = {};
