/**
 * ListTriageQueue handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listTriageQueue } from "@alertworth/api-server/domains/triage/handlers";
import type { TriageDDDDependencies } from "@alertworth/api-server/domains/triage";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alertworth/tests/shared";
import { TRIAGE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListTriageQueue", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TriageDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TriageDDDDependencies>(
      TRIAGE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListTriageQueue, "execute").mockResolvedValue(useCaseResult);

    await listTriageQueue(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListTriageQueue.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
