/**
 * Handlers for Kri
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IndicatorsDomainModule } from "../dependencies/indicators-ddd.dependencies.js";
import type { DefineKeyRiskIndicatorInput, ListKeyRiskIndicatorsInput } from "@alertworth/services/indicators";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/kris
 * Operation: listKeyRiskIndicators
 */
export async function listKeyRiskIndicators(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: IndicatorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListKeyRiskIndicatorsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.kris.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/kris
 * Operation: defineKeyRiskIndicator
 */
export async function defineKeyRiskIndicator(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: IndicatorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DefineKeyRiskIndicatorInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.kris.get.execute(input);
  return reply.code(201).send(result);
}


