/**
 * Handlers for Refresh
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IndicatorsDomainModule } from "../dependencies/indicators-ddd.dependencies.js";
import type { RefreshKeyRiskIndicatorInput } from "@alertworth/services/indicators";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/kris/{kriId}/refresh
 * Operation: refreshKeyRiskIndicator
 */
export async function refreshKeyRiskIndicator(
  request: FastifyRequest<{ Params: { kriId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IndicatorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RefreshKeyRiskIndicatorInput = {
    kriId: request.params.kriId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.refreshes.update.execute(input);
  return reply.code(200).send(result);
}


