/**
 * AnomalyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnomalyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AnomalyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AnomalyRepository,
} from "@alertworth/services/baselines";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AnomalyRepositoryDdb } from "./anomaly-repository.ddb.js";

/**
 * AnomalyRepositoryAdapter
 *
 * Implements AnomalyRepository port for infrastructure layer.
 */
export class AnomalyRepositoryAdapter implements AnomalyRepository {
  private readonly ddb: AnomalyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AnomalyRepositoryDdb(this.dynamoClient);
  }

  async listAnomalyDetections(input: Parameters<AnomalyRepository['listAnomalyDetections']>[0]): Promise<Awaited<ReturnType<AnomalyRepository['listAnomalyDetections']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnomalyDetections(input);
  }
}
