/**
 * AttackPathRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttackPathRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AttackPathRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AttackPathRepository,
} from "@alertworth/services/baselines";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AttackPathRepositoryDdb } from "./attack-path-repository.ddb.js";

/**
 * AttackPathRepositoryAdapter
 *
 * Implements AttackPathRepository port for infrastructure layer.
 */
export class AttackPathRepositoryAdapter implements AttackPathRepository {
  private readonly ddb: AttackPathRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AttackPathRepositoryDdb(this.dynamoClient);
  }

  async listAttackPaths(input: Parameters<AttackPathRepository['listAttackPaths']>[0]): Promise<Awaited<ReturnType<AttackPathRepository['listAttackPaths']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAttackPaths(input);
  }
}
