/**
 * BaselineRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BaselineRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BaselineRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BaselineRepository,
} from "@alertworth/services/baselines";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BaselineRepositoryDdb } from "./baseline-repository.ddb.js";

/**
 * BaselineRepositoryAdapter
 *
 * Implements BaselineRepository port for infrastructure layer.
 */
export class BaselineRepositoryAdapter implements BaselineRepository {
  private readonly ddb: BaselineRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BaselineRepositoryDdb(this.dynamoClient);
  }

  async listBehaviourBaselines(input: Parameters<BaselineRepository['listBehaviourBaselines']>[0]): Promise<Awaited<ReturnType<BaselineRepository['listBehaviourBaselines']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBehaviourBaselines(input);
  }

  async createBehaviourBaseline(input: Parameters<BaselineRepository['createBehaviourBaseline']>[0]): Promise<Awaited<ReturnType<BaselineRepository['createBehaviourBaseline']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createBehaviourBaseline(input);
  }
}
