/**
 * Repository interface for Investigation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  InvestigationEntity
} from "../models/investigation.entity.js";
import type {
  ListInvestigationsParams,
  InvestigationCase
} from "../types/index.js";
/**
 * InvestigationRepository Interface
 */
export interface InvestigationRepository extends CreateReadRepository<InvestigationEntity, InvestigationCase, string, ListInvestigationsParams> {

}
