/**
 * ExecuteListAttackPaths - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAttackPaths Use Case
 *
 * DDD: Application use case for list AttackPath.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAttackPathsInput, ListAttackPathsOutput } from "../dto/attack-path.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { AttackPathRepository } from "../ports";

export class ExecuteListAttackPaths {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attackPath: AttackPathRepository
  ) {}

  async execute(input: ListAttackPathsInput): Promise<ListAttackPathsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bslId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.attackPath.listAttackPaths({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAttackPathsOutput;
  }
}
