/**
 * ExecuteListBehaviourBaselines - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBehaviourBaselines Use Case
 *
 * DDD: Application use case for list Baseline.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBehaviourBaselinesInput, ListBehaviourBaselinesOutput } from "../dto/baseline.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { BaselineRepository } from "../ports";

export class ExecuteListBehaviourBaselines {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly baseline: BaselineRepository
  ) {}

  async execute(input: ListBehaviourBaselinesInput): Promise<ListBehaviourBaselinesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bslId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.baseline.listBehaviourBaselines({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBehaviourBaselinesOutput;
  }
}
