/**
 * BackTestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BackTestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BackTestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BackTestRepository,
} from "@alertworth/services/scoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BackTestRepositoryDdb } from "./back-test-repository.ddb.js";

/**
 * BackTestRepositoryAdapter
 *
 * Implements BackTestRepository port for infrastructure layer.
 */
export class BackTestRepositoryAdapter implements BackTestRepository {
  private readonly ddb: BackTestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BackTestRepositoryDdb(this.dynamoClient);
  }

  async runDismissalBackTest(input: Parameters<BackTestRepository['runDismissalBackTest']>[0]): Promise<Awaited<ReturnType<BackTestRepository['runDismissalBackTest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.runDismissalBackTest(input);
  }
}
