/**
 * DismissalPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DismissalPolicyRepository Port
 *
 * DDD: Application port for dismissalpolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDismissalPolicyInput, CreateDismissalPolicyOutput, ListDismissalPoliciesInput, ListDismissalPoliciesOutput } from "../dto/dismissal-policy.dto";
export interface DismissalPolicyRepository {
  listDismissalPolicies(input: ListDismissalPoliciesInput): Promise<ListDismissalPoliciesOutput>;
  createDismissalPolicy(input: CreateDismissalPolicyInput): Promise<CreateDismissalPolicyOutput>;
}

export type { CreateDismissalPolicyInput, CreateDismissalPolicyOutput, ListDismissalPoliciesInput, ListDismissalPoliciesOutput } from "../dto/dismissal-policy.dto";
