/**
 * CyberRiskAppetite Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CyberRiskAppetiteEntity } from "@alertworth/core/reporting/models/index.js";
import { reportingSchemas } from "@alertworth/core/reporting";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rpt";

export function createCyberRiskAppetite(overrides: Partial<CyberRiskAppetiteEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cra_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    narrative: overrides.narrative ?? faker.lorem.word(),
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return reportingSchemas.CyberRiskAppetite.parse(raw);
}

export function cyberRiskAppetiteBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCyberRiskAppetite(overrides));
}
