/**
 * Routes for ContainmentAction
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { executeContainmentAction } from "../handlers/containment-action.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function containmentActionRoutes(fastify: FastifyInstance) {
  // POST /v1/containment-actions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/containment-actions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTriageDependenciesForRequest();
        await executeContainmentAction(request, reply, deps);
      });
    }
  );


}
