/**
 * Routes for Override
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { overrideContainmentAction } from "../handlers/override.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function overrideRoutes(fastify: FastifyInstance) {
  // POST /v1/containment-actions/{actionId}/override (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/containment-actions/:actionId/override",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { actionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTriageDependenciesForRequest();
        await overrideContainmentAction(request, reply, deps);
      });
    }
  );


}
