/**
 * Handlers for Approve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScoringDomainModule } from "../dependencies/scoring-ddd.dependencies.js";
import type { ApproveDismissalPolicyInput } from "@alertworth/services/scoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/dismissal-policies/{policyId}/approve
 * Operation: approveDismissalPolicy
 */
export async function approveDismissalPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApproveDismissalPolicyInput = {
    policyId: request.params.policyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.approves.create.execute(input);
  return reply.code(200).send(result);
}


