/**
 * Handlers for DismissalPolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScoringDomainModule } from "../dependencies/scoring-ddd.dependencies.js";
import type { CreateDismissalPolicyInput, ListDismissalPoliciesInput } from "@alertworth/services/scoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/dismissal-policies
 * Operation: listDismissalPolicies
 */
export async function listDismissalPolicies(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDismissalPoliciesInput = {};
  const result = await deps.useCases.dismissalPolicies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/dismissal-policies
 * Operation: createDismissalPolicy
 */
export async function createDismissalPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDismissalPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dismissalPolicies.create.execute(input);
  return reply.code(201).send(result);
}


