/**
 * Investigation Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { InvestigationEntity } from "@alertworth/core/investigations/models/index.js";
import { investigationsSchemas } from "@alertworth/core/investigations";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inv";

export function createInvestigation(overrides: Partial<InvestigationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cse_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    alertId: overrides.alertId ?? `alt_${ulid().toLowerCase()}`,
    status: overrides.status ?? "open",
    ...overrides,
  };

  return investigationsSchemas.InvestigationCase.parse(raw);
}

export function investigationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createInvestigation(overrides));
}
