/**
 * Disposition DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disposition DTOs
 *
 * DDD: Application DTOs for Disposition use cases.
 */

import type { DisposeInvestigationParams, DisposeInvestigationRequestInput } from "@alertworth/core/investigations/types";

export type DisposeInvestigationInput = DisposeInvestigationParams & DisposeInvestigationRequestInput;

export type DisposeInvestigationOutput = {};
