/**
 * Investigation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Investigation DTOs
 *
 * DDD: Application DTOs for Investigation use cases.
 */

import type { ListInvestigationsParams, OpenInvestigationRequestInput } from "@alertworth/core/investigations/types";

export type ListInvestigationsInput = ListInvestigationsParams;

export type OpenInvestigationInput = OpenInvestigationRequestInput;

export type ListInvestigationsOutput = {};

export type OpenInvestigationOutput = {};
