/**
 * CyberRiskAppetiteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CyberRiskAppetiteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CyberRiskAppetiteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CyberRiskAppetiteRepository,
} from "@alertworth/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CyberRiskAppetiteRepositoryDdb } from "./cyber-risk-appetite-repository.ddb.js";

/**
 * CyberRiskAppetiteRepositoryAdapter
 *
 * Implements CyberRiskAppetiteRepository port for infrastructure layer.
 */
export class CyberRiskAppetiteRepositoryAdapter implements CyberRiskAppetiteRepository {
  private readonly ddb: CyberRiskAppetiteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CyberRiskAppetiteRepositoryDdb(this.dynamoClient);
  }

  async getCyberRiskAppetite(input: Parameters<CyberRiskAppetiteRepository['getCyberRiskAppetite']>[0]): Promise<Awaited<ReturnType<CyberRiskAppetiteRepository['getCyberRiskAppetite']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCyberRiskAppetite(input);
  }

  async updateCyberRiskAppetite(input: Parameters<CyberRiskAppetiteRepository['updateCyberRiskAppetite']>[0]): Promise<Awaited<ReturnType<CyberRiskAppetiteRepository['updateCyberRiskAppetite']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateCyberRiskAppetite(input);
  }
}
