/**
 * ContainmentAction DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContainmentAction DTOs
 *
 * DDD: Application DTOs for ContainmentAction use cases.
 */

import type { ExecuteContainmentActionRequestInput } from "@alertworth/core/triage/types";

export type ExecuteContainmentActionInput = ExecuteContainmentActionRequestInput;

export type ExecuteContainmentActionOutput = {};
