/**
 * Overflow DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Overflow DTOs
 *
 * DDD: Application DTOs for Overflow use cases.
 */

import type { RouteOverflowRequestInput } from "@alertworth/core/triage/types";

export type RouteOverflowInput = RouteOverflowRequestInput;

export type RouteOverflowOutput = {};
