/**
 * Shift DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Shift DTOs
 *
 * DDD: Application DTOs for Shift use cases.
 */

import type { ListTriageShiftsParams, OpenTriageShiftRequestInput } from "@alertworth/core/triage/types";

export type ListTriageShiftsInput = ListTriageShiftsParams;

export type OpenTriageShiftInput = OpenTriageShiftRequestInput;

export type ListTriageShiftsOutput = {};

export type OpenTriageShiftOutput = {};
