/**
 * Repository Generator exports
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./snapshot.repository.js";
export * from "./cyber-risk-appetite.repository.js";
