/**
 * Repository interface for Snapshot
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SnapshotEntity
} from "../models/snapshot.entity.js";
import type {
  ListResidualRiskSnapshotsParams,
  ResidualRiskSnapshot
} from "../types/index.js";
/**
 * SnapshotRepository Interface
 */
export interface SnapshotRepository extends CreateReadRepository<SnapshotEntity, ResidualRiskSnapshot, string, ListResidualRiskSnapshotsParams> {

}
