/**
 * ExecuteDefineKeyRiskIndicator - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDefineKeyRiskIndicator Use Case
 *
 * DDD: Application use case for get Kri.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DefineKeyRiskIndicatorInput, DefineKeyRiskIndicatorOutput } from "../dto/kri.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { KriRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDefineKeyRiskIndicator {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly kri: KriRepository
  ) {}

  async execute(input: DefineKeyRiskIndicatorInput): Promise<DefineKeyRiskIndicatorOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.indId();

    // All field names extracted from OpenAPI spec: maxEvidenceAgeHours, minCoverage, name, ownerId, threshold
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).ownerId) {
      throw new ValidationError("ownerId is required");
    }
    const ownerId = (input as any).ownerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.kri.defineKeyRiskIndicator({ ownerId: ownerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${ownerId}`);
    }

    return entity as DefineKeyRiskIndicatorOutput;
  }
}
