/**
 * BackTest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BackTest DTOs
 *
 * DDD: Application DTOs for BackTest use cases.
 */

import type { RunDismissalBackTestParams, RunDismissalBackTestRequestInput } from "@alertworth/core/scoring/types";

export type RunDismissalBackTestInput = RunDismissalBackTestParams & RunDismissalBackTestRequestInput;

export type RunDismissalBackTestOutput = {};
