/**
 * DismissalPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DismissalPolicy DTOs
 *
 * DDD: Application DTOs for DismissalPolicy use cases.
 */

import type { CreateDismissalPolicyRequestInput } from "@alertworth/core/scoring/types";

export type ListDismissalPoliciesInput = {};

export type CreateDismissalPolicyInput = CreateDismissalPolicyRequestInput;

export type ListDismissalPoliciesOutput = {};

export type CreateDismissalPolicyOutput = {};
