/**
 * ListQueue DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTriageQueueParams } from "@alertworth/core/triage";

export function createListQueueRequest(overrides: Partial<ListTriageQueueParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
