/**
 * ListTriageShifts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listTriageShifts } from "@alertworth/api-server/domains/triage/handlers";
import type { TriageDDDDependencies } from "@alertworth/api-server/domains/triage";
import { createShift as createShiftEntity } from "@alertworth/factories/triage";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alertworth/tests/shared";
import { TRIAGE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListTriageShifts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TriageDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TriageDDDDependencies>(
      TRIAGE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createShiftEntity({ orgId }),
      createShiftEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListTriageShifts, "execute").mockResolvedValue(useCaseResult);

    await listTriageShifts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListTriageShifts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
