/**
 * UpdateCyberRiskAppetite handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateCyberRiskAppetite } from "@alertworth/api-server/domains/reporting/handlers";
import type { ReportingDDDDependencies } from "@alertworth/api-server/domains/reporting";
import { createCyberRiskAppetite as createCyberRiskAppetiteEntity } from "@alertworth/factories/reporting";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alertworth/tests/shared";
import { REPORTING_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateCyberRiskAppetite", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReportingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReportingDDDDependencies>(
      REPORTING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createCyberRiskAppetiteEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { id: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateCyberRiskAppetite, "execute").mockResolvedValue(useCaseResult);

    await updateCyberRiskAppetite(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateCyberRiskAppetite.execute).toHaveBeenCalledWith(expect.objectContaining({ id: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
