/**
 * Anomaly Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AnomalyEntity } from "@alertworth/core/baselines/models/index.js";
import { baselinesSchemas } from "@alertworth/core/baselines";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "bsl";

export function createAnomaly(overrides: Partial<AnomalyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `anm_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    baselineId: overrides.baselineId ?? `bsl_${ulid().toLowerCase()}`,
    status: overrides.status ?? "raised",
    ...overrides,
  };

  return baselinesSchemas.AnomalyDetection.parse(raw);
}

export function anomalyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAnomaly(overrides));
}
