/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @alertworth/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@alertworth/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@alertworth/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@alertworth/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@alertworth/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@alertworth/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _baselines from "./baselines/index.js";
import * as _controls from "./controls/index.js";
import * as _events from "./events/index.js";
import * as _identity from "./identity/index.js";
import * as _indicators from "./indicators/index.js";
import * as _investigations from "./investigations/index.js";
import * as _reporting from "./reporting/index.js";
import * as _scoring from "./scoring/index.js";
import * as _triage from "./triage/index.js";

// Export as namespaces
export const _shared = __shared;
export const baselines = _baselines;
export const controls = _controls;
export const events = _events;
export const identity = _identity;
export const indicators = _indicators;
export const investigations = _investigations;
export const reporting = _reporting;
export const scoring = _scoring;
export const triage = _triage;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@alertworth/core"; activity.types.*
//   - Direct exports: import * from "@alertworth/core/activity/types/index.js"
//   - Direct exports: import * from "@alertworth/core/activity/repositories/index.js"
//   - Direct exports: import * from "@alertworth/core/activity/models/index.js"
//   - Direct exports: import * from "@alertworth/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Baselines Service
export { schemas as BaselinesSchemas } from "./baselines/schemas/baselines.schemas.js";

// Controls Service
export { schemas as ControlsSchemas } from "./controls/schemas/controls.schemas.js";

// Events Service
export { schemas as EventsSchemas } from "./events/schemas/events.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Indicators Service
export { schemas as IndicatorsSchemas } from "./indicators/schemas/indicators.schemas.js";

// Investigations Service
export { schemas as InvestigationsSchemas } from "./investigations/schemas/investigations.schemas.js";

// Reporting Service
export { schemas as ReportingSchemas } from "./reporting/schemas/reporting.schemas.js";

// Scoring Service
export { schemas as ScoringSchemas } from "./scoring/schemas/scoring.schemas.js";

// Triage Service
export { schemas as TriageSchemas } from "./triage/schemas/triage.schemas.js";

