/**
 * ExecuteCreateDismissalPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDismissalPolicy Use Case
 *
 * DDD: Application use case for create DismissalPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDismissalPolicyInput, CreateDismissalPolicyOutput } from "../dto/dismissal-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { DismissalPolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDismissalPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dismissalPolicy: DismissalPolicyRepository
  ) {}

  async execute(input: CreateDismissalPolicyInput): Promise<CreateDismissalPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: alertClass, name, ownerId, rules
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.alertClass) {
      throw new ValidationError("alertClass is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (scoring domain)
    const entityId = this.idGenerator.scrId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.dismissalPolicy.createDismissalPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDismissalPolicyOutput;
  }
}
