/**
 * ExecuteListDismissalPolicies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDismissalPolicies Use Case
 *
 * DDD: Application use case for list DismissalPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDismissalPoliciesInput, ListDismissalPoliciesOutput } from "../dto/dismissal-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { DismissalPolicyRepository } from "../ports";

export class ExecuteListDismissalPolicies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dismissalPolicy: DismissalPolicyRepository
  ) {}

  async execute(input: ListDismissalPoliciesInput): Promise<ListDismissalPoliciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dismissalPolicy.listDismissalPolicies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDismissalPoliciesOutput;
  }
}
