/**
 * CommitteePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CommitteePack DTOs
 *
 * DDD: Application DTOs for CommitteePack use cases.
 */

import type { AssembleCommitteePackRequestInput } from "@alertworth/core/reporting/types";

export type AssembleCommitteePackInput = AssembleCommitteePackRequestInput;

export type AssembleCommitteePackOutput = {};
