/**
 * Kri DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Kri DTOs
 *
 * DDD: Application DTOs for Kri use cases.
 */

import type { DefineKeyRiskIndicatorRequestInput, ListKeyRiskIndicatorsParams } from "@alertworth/core/indicators/types";

export type ListKeyRiskIndicatorsInput = ListKeyRiskIndicatorsParams;

export type DefineKeyRiskIndicatorInput = DefineKeyRiskIndicatorRequestInput;

export type ListKeyRiskIndicatorsOutput = {};

export type DefineKeyRiskIndicatorOutput = {};
