/**
 * Refresh DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Refresh DTOs
 *
 * DDD: Application DTOs for Refresh use cases.
 */

import type { RefreshKeyRiskIndicatorParams, RefreshKeyRiskIndicatorRequestInput } from "@alertworth/core/indicators/types";

export type RefreshKeyRiskIndicatorInput = RefreshKeyRiskIndicatorParams & RefreshKeyRiskIndicatorRequestInput;

export type RefreshKeyRiskIndicatorOutput = {};
