/**
 * ExecuteOpenTriageShift - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenTriageShift Use Case
 *
 * DDD: Application use case for get Shift.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenTriageShiftInput, OpenTriageShiftOutput } from "../dto/shift.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { ShiftRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenTriageShift {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly shift: ShiftRepository
  ) {}

  async execute(input: OpenTriageShiftInput): Promise<OpenTriageShiftOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trgId();

    // All field names extracted from OpenAPI spec: accountableLeadId, capacitySlots, endsAt, startsAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).accountableLeadId) {
      throw new ValidationError("accountableLeadId is required");
    }
    const accountableleadId = (input as any).accountableLeadId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.shift.openTriageShift({ accountableLeadId: accountableleadId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${accountableleadId}`);
    }

    return entity as OpenTriageShiftOutput;
  }
}
