/**
 * CyberRiskAppetiteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CyberRiskAppetiteRepository Port
 *
 * DDD: Application port for cyberriskappetiterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCyberRiskAppetiteInput, GetCyberRiskAppetiteOutput, UpdateCyberRiskAppetiteInput, UpdateCyberRiskAppetiteOutput } from "../dto/cyber-risk-appetite.dto";
export interface CyberRiskAppetiteRepository {
  getCyberRiskAppetite(input: GetCyberRiskAppetiteInput): Promise<GetCyberRiskAppetiteOutput>;
  updateCyberRiskAppetite(input: UpdateCyberRiskAppetiteInput): Promise<UpdateCyberRiskAppetiteOutput>;
}

export type { GetCyberRiskAppetiteInput, GetCyberRiskAppetiteOutput, UpdateCyberRiskAppetiteInput, UpdateCyberRiskAppetiteOutput } from "../dto/cyber-risk-appetite.dto";
