/**
 * SnapshotRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SnapshotRepository Port
 *
 * DDD: Application port for snapshotrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListResidualRiskSnapshotsInput, ListResidualRiskSnapshotsOutput } from "../dto/snapshot.dto";
export interface SnapshotRepository {
  listResidualRiskSnapshots(input: ListResidualRiskSnapshotsInput): Promise<ListResidualRiskSnapshotsOutput>;
}

export type { ListResidualRiskSnapshotsInput, ListResidualRiskSnapshotsOutput } from "../dto/snapshot.dto";
