/**
 * ExecuteScheduleControlTest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScheduleControlTest Use Case
 *
 * DDD: Application use case for get ControlTest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScheduleControlTestInput, ScheduleControlTestOutput } from "../dto/control-test.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { ControlTestRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScheduleControlTest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly controlTest: ControlTestRepository
  ) {}

  async execute(input: ScheduleControlTestInput): Promise<ScheduleControlTestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ctlId();

    // All field names extracted from OpenAPI spec: controlId, ownerId, schedule
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).controlId) {
      throw new ValidationError("controlId is required");
    }
    const controlId = (input as any).controlId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.controlTest.scheduleControlTest({ controlId: controlId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${controlId}`);
    }

    return entity as ScheduleControlTestOutput;
  }
}
