/**
 * ExecuteOpenInvestigation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenInvestigation Use Case
 *
 * DDD: Application use case for get Investigation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenInvestigationInput, OpenInvestigationOutput } from "../dto/investigation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { InvestigationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenInvestigation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly investigation: InvestigationRepository
  ) {}

  async execute(input: OpenInvestigationInput): Promise<OpenInvestigationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: alertId, analystId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).alertId) {
      throw new ValidationError("alertId is required");
    }
    const alertId = (input as any).alertId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.investigation.openInvestigation({ alertId: alertId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${alertId}`);
    }

    return entity as OpenInvestigationOutput;
  }
}
