/**
 * ExecutePublishResidualRiskSnapshot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePublishResidualRiskSnapshot Use Case
 *
 * DDD: Application use case for get Snapshot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PublishResidualRiskSnapshotInput, PublishResidualRiskSnapshotOutput } from "../dto/snapshot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { SnapshotPublisher, SnapshotRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecutePublishResidualRiskSnapshot {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly snapshotRepository: SnapshotRepository,
    private readonly snapshotPublisher: SnapshotPublisher
  ) {}

  async execute(input: PublishResidualRiskSnapshotInput): Promise<PublishResidualRiskSnapshotOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: asOf, audience
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.snapshotPublisher.publishResidualRiskSnapshot({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as PublishResidualRiskSnapshotOutput;
  }
}
