/**
 * ExecuteGetCyberRiskAppetite - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCyberRiskAppetite Use Case
 *
 * DDD: Application use case for get CyberRiskAppetite.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCyberRiskAppetiteInput, GetCyberRiskAppetiteOutput } from "../dto/cyber-risk-appetite.dto";
import type { ExecutionContextService, IdGeneratorService } from "@alertworth/services/_shared/index.js";
import type { CyberRiskAppetiteRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetCyberRiskAppetite {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cyberRiskAppetite: CyberRiskAppetiteRepository
  ) {}

  async execute(input: GetCyberRiskAppetiteInput): Promise<GetCyberRiskAppetiteOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.cyberRiskAppetite.getCyberRiskAppetite({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetCyberRiskAppetiteOutput;
  }
}
