/**
 * Shift Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/triage.openapi.types.js";
import { schemas } from "../schemas/triage.schemas.js";

/**
 * Entity: ShiftEntity
 * Description: Represents the Shift domain model.
 * Source: schemas.TriageShift
 * Type: Persisted Entity (x-dynamodb)
 */
export const ShiftEntitySchema = schemas.TriageShift;
export type ShiftEntity = components["schemas"]["TriageShift"];
