/**
 * Repository interface for Alert
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AlertEntity
} from "../models/alert.entity.js";
import type {
  ListAlertsParams
} from "../types/index.js";
/**
 * AlertRepository Interface
 */
export interface AlertRepository extends ReadRepository<AlertEntity, string, ListAlertsParams> {

}
