/**
 * Repository interface for Anomaly
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AnomalyEntity
} from "../models/anomaly.entity.js";
import type {
  ListAnomalyDetectionsParams
} from "../types/index.js";
/**
 * AnomalyRepository Interface
 */
export interface AnomalyRepository extends ReadRepository<AnomalyEntity, string, ListAnomalyDetectionsParams> {

}
