/**
 * Repository interface for AttackPath
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AttackPathEntity
} from "../models/attack-path.entity.js";
import type {
  ListAttackPathsParams
} from "../types/index.js";
/**
 * AttackPathRepository Interface
 */
export interface AttackPathRepository extends ReadRepository<AttackPathEntity, string, ListAttackPathsParams> {

}
