/**
 * Repository interface for Baseline
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BaselineEntity
} from "../models/baseline.entity.js";
import type {
  ListBehaviourBaselinesParams,
  BehaviourBaseline
} from "../types/index.js";
/**
 * BaselineRepository Interface
 */
export interface BaselineRepository extends CreateReadRepository<BaselineEntity, BehaviourBaseline, string, ListBehaviourBaselinesParams> {

}
