/**
 * ActivateBehaviourBaseline handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { activateBehaviourBaseline } from "@alertworth/api-server/domains/baselines/handlers";
import type { BaselinesDDDDependencies } from "@alertworth/api-server/domains/baselines";
import { createCreateActivateRequest } from "@alertworth/factories/baselines";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alertworth/tests/shared";
import { BASELINES_USE_CASES } from "../__factories__/use-cases.js";

describe("ActivateBehaviourBaseline", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BaselinesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BaselinesDDDDependencies>(
      BASELINES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateActivateRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeActivateBehaviourBaseline, "execute").mockResolvedValue(useCaseResult);

    await activateBehaviourBaseline(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeActivateBehaviourBaseline.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
