/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildBaselinesDomainModule } from "./baselines/dependencies/baselines-ddd.dependencies.js";
export { buildControlsDomainModule } from "./controls/dependencies/controls-ddd.dependencies.js";
export { buildEventsDomainModule } from "./events/dependencies/events-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildIndicatorsDomainModule } from "./indicators/dependencies/indicators-ddd.dependencies.js";
export { buildInvestigationsDomainModule } from "./investigations/dependencies/investigations-ddd.dependencies.js";
export { buildReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export { buildScoringDomainModule } from "./scoring/dependencies/scoring-ddd.dependencies.js";
export { buildTriageDomainModule } from "./triage/dependencies/triage-ddd.dependencies.js";

// Export all domain dependency types
export type { BaselinesDomainModule } from "./baselines/dependencies/baselines-ddd.dependencies.js";
export type { ControlsDomainModule } from "./controls/dependencies/controls-ddd.dependencies.js";
export type { EventsDomainModule } from "./events/dependencies/events-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { IndicatorsDomainModule } from "./indicators/dependencies/indicators-ddd.dependencies.js";
export type { InvestigationsDomainModule } from "./investigations/dependencies/investigations-ddd.dependencies.js";
export type { ReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export type { ScoringDomainModule } from "./scoring/dependencies/scoring-ddd.dependencies.js";
export type { TriageDomainModule } from "./triage/dependencies/triage-ddd.dependencies.js";
