/**
 * AttackPath Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/baselines.openapi.types.js";
import { schemas } from "../schemas/baselines.schemas.js";

/**
 * Entity: AttackPathEntity
 * Description: Represents the AttackPath domain model.
 * Source: schemas.AttackPath
 * Type: Persisted Entity (x-dynamodb)
 */
export const AttackPathEntitySchema = schemas.AttackPath;
export type AttackPathEntity = components["schemas"]["AttackPath"];
