/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the baselines domain.
 * Use these factories in tests to create test data.
 */

export { createAnomaly } from "./anomaly/entity/anomaly.entity.factory.js";
export { createAttackPath } from "./attack-path/entity/attack-path.entity.factory.js";
export { createBaseline } from "./baseline/entity/baseline.entity.factory.js";
export { createCreateActivateRequest } from "./activate/dto/create-activate.dto.factory.js";
