/**
 * Investigations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Investigations Domain Module - Composition root
 *
 * DDD: Composition root for investigations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ChallengeDismissalRepositoryAdapter,
  DispositionRepositoryAdapter,
  InvestigationRepositoryAdapter,
} from "@alertworth/adapters/investigations";
import { getIdGeneratorService } from "@alertworth/adapters";
import type { AdapterDynamoDBClient } from "@alertworth/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListInvestigations,
  ExecuteOpenInvestigation,
} from "@alertworth/services/investigations/usecases";
// Ports (interfaces)
import type {
  ChallengeDismissalRepository,
  DispositionRepository,
  InvestigationRepository,
} from "@alertworth/services/investigations/ports";

export interface InvestigationsDomainModule {
  repos: {
    challengeDismissals: ChallengeDismissalRepository;
    dispositions: DispositionRepository;
    investigations: InvestigationRepository;
  };
  useCases: {
    investigations: {
      get: ExecuteOpenInvestigation;
      list: ExecuteListInvestigations;
    };
  };
}

export function buildInvestigationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): InvestigationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      challengeDismissals?: ChallengeDismissalRepository;
      dispositions?: DispositionRepository;
      investigations?: InvestigationRepository;
    } = {};

    obj.challengeDismissals = new ChallengeDismissalRepositoryAdapter(dynamoClient);
    obj.dispositions = new DispositionRepositoryAdapter(dynamoClient);
    obj.investigations = new InvestigationRepositoryAdapter(dynamoClient);
    return {
      challengeDismissals: obj.challengeDismissals!,
      dispositions: obj.dispositions!,
      investigations: obj.investigations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    investigations: {
      get: new ExecuteOpenInvestigation(executionContext, idGenerator, repos.investigations),
      list: new ExecuteListInvestigations(executionContext, idGenerator, repos.investigations),
    },
  };
  return { repos, useCases: useCases as InvestigationsDomainModule["useCases"] };
}
