/**
 * AttackPath Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AttackPathEntity } from "@alertworth/core/baselines/models/index.js";
import { baselinesSchemas } from "@alertworth/core/baselines";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "bsl";

export function createAttackPath(overrides: Partial<AttackPathEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ath_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    entryPoint: overrides.entryPoint ?? faker.lorem.word(),
    status: overrides.status ?? "recommended",
    ...overrides,
  };

  return baselinesSchemas.AttackPath.parse(raw);
}

export function attackPathBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAttackPath(overrides));
}
