/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./challenge-dismissal-repository.ddb.js";
export * from "./disposition-repository.ddb.js";
export * from "./investigation-repository.ddb.js";
export * from "./challenge-dismissal-repository.adapter.js";
export * from "./disposition-repository.adapter.js";
export * from "./investigation-repository.adapter.js";
