/**
 * InvestigationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InvestigationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InvestigationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InvestigationRepository,
} from "@alertworth/services/investigations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InvestigationRepositoryDdb } from "./investigation-repository.ddb.js";

/**
 * InvestigationRepositoryAdapter
 *
 * Implements InvestigationRepository port for infrastructure layer.
 */
export class InvestigationRepositoryAdapter implements InvestigationRepository {
  private readonly ddb: InvestigationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InvestigationRepositoryDdb(this.dynamoClient);
  }

  async listInvestigations(input: Parameters<InvestigationRepository['listInvestigations']>[0]): Promise<Awaited<ReturnType<InvestigationRepository['listInvestigations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listInvestigations(input);
  }

  async openInvestigation(input: Parameters<InvestigationRepository['openInvestigation']>[0]): Promise<Awaited<ReturnType<InvestigationRepository['openInvestigation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openInvestigation(input);
  }
}
