/**
 * Handlers for Activate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BaselinesDomainModule } from "../dependencies/baselines-ddd.dependencies.js";
import type { ActivateBehaviourBaselineInput } from "@alertworth/services/baselines";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/baselines/{baselineId}/activate
 * Operation: activateBehaviourBaseline
 */
export async function activateBehaviourBaseline(
  request: FastifyRequest<{ Params: { baselineId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BaselinesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ActivateBehaviourBaselineInput = {
    baselineId: request.params.baselineId,
  };
  const result = await deps.useCases.activates.get.execute(input);
  return reply.code(200).send(result);
}


