/**
 * Handlers for Baseline
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BaselinesDomainModule } from "../dependencies/baselines-ddd.dependencies.js";
import type { CreateBehaviourBaselineInput, ListBehaviourBaselinesInput } from "@alertworth/services/baselines";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/baselines
 * Operation: listBehaviourBaselines
 */
export async function listBehaviourBaselines(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BaselinesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBehaviourBaselinesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.baselines.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/baselines
 * Operation: createBehaviourBaseline
 */
export async function createBehaviourBaseline(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BaselinesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateBehaviourBaselineInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.baselines.create.execute(input);
  return reply.code(201).send(result);
}


