/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BaselinesDomainModule } from "../dependencies/baselines-ddd.dependencies.js";
import type { DecideAttackPathRecommendationInput } from "@alertworth/services/baselines";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/attack-paths/{pathId}/decision
 * Operation: decideAttackPathRecommendation
 */
export async function decideAttackPathRecommendation(
  request: FastifyRequest<{ Params: { pathId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BaselinesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideAttackPathRecommendationInput = {
    pathId: request.params.pathId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(200).send(result);
}


