/**
 * Repository interface for ContainmentAction
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ContainmentActionEntity
} from "../models/containment-action.entity.js";
import type {
  ContainmentAction
} from "../types/index.js";
/**
 * ContainmentActionRepository Interface
 */
export interface ContainmentActionRepository extends CreateReadRepository<ContainmentActionEntity, ContainmentAction, string, Record<string, never>> {

}
