/**
 * Repository interface for Shift
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ShiftEntity
} from "../models/shift.entity.js";
import type {
  ListTriageShiftsParams,
  TriageShift
} from "../types/index.js";
/**
 * ShiftRepository Interface
 */
export interface ShiftRepository extends CreateReadRepository<ShiftEntity, TriageShift, string, ListTriageShiftsParams> {

}
