/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@alertworth/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@alertworth/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@alertworth/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _baselines from "./baselines/index.js";
import * as _controls from "./controls/index.js";
import * as _events from "./events/index.js";
import * as _identity from "./identity/index.js";
import * as _indicators from "./indicators/index.js";
import * as _investigations from "./investigations/index.js";
import * as _reporting from "./reporting/index.js";
import * as _scoring from "./scoring/index.js";
import * as _triage from "./triage/index.js";

// Export as namespaces
export const baselines = _baselines;
export const controls = _controls;
export const events = _events;
export const identity = _identity;
export const indicators = _indicators;
export const investigations = _investigations;
export const reporting = _reporting;
export const scoring = _scoring;
export const triage = _triage;
