/**
 * ChallengeDismissalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChallengeDismissalRepository Port
 *
 * DDD: Application port for challengedismissalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ChallengeAutoDismissalInput, ChallengeAutoDismissalOutput } from "../dto/challenge-dismissal.dto";
export interface ChallengeDismissalRepository {
  challengeAutoDismissal(input: ChallengeAutoDismissalInput): Promise<ChallengeAutoDismissalOutput>;
}

export type { ChallengeAutoDismissalInput, ChallengeAutoDismissalOutput } from "../dto/challenge-dismissal.dto";
