/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { alertRoutes } from "./alert.routes.js";
export { dismissalPolicyRoutes } from "./dismissal-policy.routes.js";
export { approveRoutes } from "./approve.routes.js";
export { backTestRoutes } from "./back-test.routes.js";
export { scoreRoutes } from "./score.routes.js";
