/**
 * ListBaseline DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListBehaviourBaselinesParams } from "@alertworth/core/baselines";

export function createListBaselineRequest(overrides: Partial<ListBehaviourBaselinesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
