/**
 * Routes for ChallengeDismissal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { challengeAutoDismissal } from "../handlers/challenge-dismissal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function challengeDismissalRoutes(fastify: FastifyInstance) {
  // POST /v1/investigations/{caseId}/challenge-dismissal (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/investigations/:caseId/challenge-dismissal",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInvestigationsDependenciesForRequest();
        await challengeAutoDismissal(request, reply, deps);
      });
    }
  );


}
