/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { investigationRoutes } from "./investigation.routes.js";
export { challengeDismissalRoutes } from "./challenge-dismissal.routes.js";
export { dispositionRoutes } from "./disposition.routes.js";
