/**
 * ListKeyRiskIndicators handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listKeyRiskIndicators } from "@alertworth/api-server/domains/indicators/handlers";
import type { IndicatorsDDDDependencies } from "@alertworth/api-server/domains/indicators";
import { createKri as createKriEntity } from "@alertworth/factories/indicators";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@alertworth/tests/shared";
import { INDICATORS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListKeyRiskIndicators", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IndicatorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IndicatorsDDDDependencies>(
      INDICATORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createKriEntity({ orgId }),
      createKriEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListKeyRiskIndicators, "execute").mockResolvedValue(useCaseResult);

    await listKeyRiskIndicators(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListKeyRiskIndicators.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
