/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: controls
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the controls domain.
 * Use these factories in tests to create test data.
 */

export { createControlTest } from "./control-test/entity/control-test.entity.factory.js";
export { createControlTestResult } from "./control-test-result/entity/control-test-result.entity.factory.js";
