/**
 * Scoring DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scoring Domain Module - Composition root
 *
 * DDD: Composition root for scoring domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AlertRepositoryAdapter,
  ApproveRepositoryAdapter,
  BackTestRepositoryAdapter,
  DismissalPolicyRepositoryAdapter,
  ScoreRepositoryAdapter,
} from "@alertworth/adapters/scoring";
import { getIdGeneratorService } from "@alertworth/adapters";
import type { AdapterDynamoDBClient } from "@alertworth/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDismissalPolicy,
  ExecuteGetAlertEconomicScore,
  ExecuteListAlerts,
  ExecuteListDismissalPolicies,
} from "@alertworth/services/scoring/usecases";
// Ports (interfaces)
import type {
  AlertRepository,
  ApproveRepository,
  BackTestRepository,
  DismissalPolicyRepository,
  ScoreRepository,
} from "@alertworth/services/scoring/ports";

export interface ScoringDomainModule {
  repos: {
    alerts: AlertRepository;
    approves: ApproveRepository;
    backTests: BackTestRepository;
    dismissalPolicies: DismissalPolicyRepository;
    scores: ScoreRepository;
  };
  useCases: {
    alerts: {
      list: ExecuteListAlerts;
    };
    dismissalPolicies: {
      create: ExecuteCreateDismissalPolicy;
      list: ExecuteListDismissalPolicies;
    };
    scores: {
      get: ExecuteGetAlertEconomicScore;
    };
  };
}

export function buildScoringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ScoringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      alerts?: AlertRepository;
      approves?: ApproveRepository;
      backTests?: BackTestRepository;
      dismissalPolicies?: DismissalPolicyRepository;
      scores?: ScoreRepository;
    } = {};

    obj.alerts = new AlertRepositoryAdapter(dynamoClient);
    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.backTests = new BackTestRepositoryAdapter(dynamoClient);
    obj.dismissalPolicies = new DismissalPolicyRepositoryAdapter(dynamoClient);
    obj.scores = new ScoreRepositoryAdapter(dynamoClient);
    return {
      alerts: obj.alerts!,
      approves: obj.approves!,
      backTests: obj.backTests!,
      dismissalPolicies: obj.dismissalPolicies!,
      scores: obj.scores!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    alerts: {
      list: new ExecuteListAlerts(executionContext, idGenerator, repos.alerts),
    },
    dismissalPolicies: {
      create: new ExecuteCreateDismissalPolicy(executionContext, idGenerator, repos.dismissalPolicies),
      list: new ExecuteListDismissalPolicies(executionContext, idGenerator, repos.dismissalPolicies),
    },
    scores: {
      get: new ExecuteGetAlertEconomicScore(executionContext, idGenerator, repos.scores),
    },
  };
  return { repos, useCases: useCases as ScoringDomainModule["useCases"] };
}
