/**
 * RefreshRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefreshRepository Port
 *
 * DDD: Application port for refreshrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RefreshKeyRiskIndicatorInput, RefreshKeyRiskIndicatorOutput } from "../dto/refresh.dto";
export interface RefreshRepository {
  refreshKeyRiskIndicator(input: RefreshKeyRiskIndicatorInput): Promise<RefreshKeyRiskIndicatorOutput>;
}

export type { RefreshKeyRiskIndicatorInput, RefreshKeyRiskIndicatorOutput } from "../dto/refresh.dto";
