/**
 * AttackPathRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttackPathRepository Port
 *
 * DDD: Application port for attackpathrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAttackPathsInput, ListAttackPathsOutput } from "../dto/attack-path.dto";
export interface AttackPathRepository {
  listAttackPaths(input: ListAttackPathsInput): Promise<ListAttackPathsOutput>;
}

export type { ListAttackPathsInput, ListAttackPathsOutput } from "../dto/attack-path.dto";
