/**
 * CyberRiskAppetite Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/reporting.openapi.types.js";
import { schemas } from "../schemas/reporting.schemas.js";

/**
 * Entity: CyberRiskAppetiteEntity
 * Description: Represents the CyberRiskAppetite domain model.
 * Source: schemas.CyberRiskAppetite
 * Type: Persisted Entity (x-dynamodb)
 */
export const CyberRiskAppetiteEntitySchema = schemas.CyberRiskAppetite;
export type CyberRiskAppetiteEntity = components["schemas"]["CyberRiskAppetite"];
