/**
 * Triage DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Triage Domain Module - Composition root
 *
 * DDD: Composition root for triage domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AdmitRepositoryAdapter,
  ContainmentActionRepositoryAdapter,
  OverflowRepositoryAdapter,
  OverrideRepositoryAdapter,
  QueueRepositoryAdapter,
  ShiftRepositoryAdapter,
} from "@alertworth/adapters/triage";
import { getIdGeneratorService } from "@alertworth/adapters";
import type { AdapterDynamoDBClient } from "@alertworth/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExecuteContainmentAction,
  ExecuteListTriageQueue,
  ExecuteListTriageShifts,
  ExecuteOpenTriageShift,
} from "@alertworth/services/triage/usecases";
// Ports (interfaces)
import type {
  AdmitRepository,
  ContainmentActionRepository,
  OverflowRepository,
  OverrideRepository,
  QueueRepository,
  ShiftRepository,
} from "@alertworth/services/triage/ports";

export interface TriageDomainModule {
  repos: {
    admits: AdmitRepository;
    containmentActions: ContainmentActionRepository;
    overflows: OverflowRepository;
    overrides: OverrideRepository;
    queues: QueueRepository;
    shifts: ShiftRepository;
  };
  useCases: {
    containmentActions: {
      create: ExecuteExecuteContainmentAction;
    };
    queues: {
      list: ExecuteListTriageQueue;
    };
    shifts: {
      get: ExecuteOpenTriageShift;
      list: ExecuteListTriageShifts;
    };
  };
}

export function buildTriageDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TriageDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      admits?: AdmitRepository;
      containmentActions?: ContainmentActionRepository;
      overflows?: OverflowRepository;
      overrides?: OverrideRepository;
      queues?: QueueRepository;
      shifts?: ShiftRepository;
    } = {};

    obj.admits = new AdmitRepositoryAdapter(dynamoClient);
    obj.containmentActions = new ContainmentActionRepositoryAdapter(dynamoClient);
    obj.overflows = new OverflowRepositoryAdapter(dynamoClient);
    obj.overrides = new OverrideRepositoryAdapter(dynamoClient);
    obj.queues = new QueueRepositoryAdapter(dynamoClient);
    obj.shifts = new ShiftRepositoryAdapter(dynamoClient);
    return {
      admits: obj.admits!,
      containmentActions: obj.containmentActions!,
      overflows: obj.overflows!,
      overrides: obj.overrides!,
      queues: obj.queues!,
      shifts: obj.shifts!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    containmentActions: {
      create: new ExecuteExecuteContainmentAction(executionContext, idGenerator, repos.containmentActions),
    },
    queues: {
      list: new ExecuteListTriageQueue(executionContext, idGenerator, repos.queues),
    },
    shifts: {
      get: new ExecuteOpenTriageShift(executionContext, idGenerator, repos.shifts),
      list: new ExecuteListTriageShifts(executionContext, idGenerator, repos.shifts),
    },
  };
  return { repos, useCases: useCases as TriageDomainModule["useCases"] };
}
