/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: baselines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Baselines Domain Use Cases
 * 
 * List of all use case names for the baselines domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BASELINES_USE_CASES = [
  "executeActivateBehaviourBaseline",
  "executeCreateBehaviourBaseline",
  "executeDecideAttackPathRecommendation",
  "executeListAnomalyDetections",
  "executeListAttackPaths",
  "executeListBehaviourBaselines"
] as const;
