/**
 * AdmitRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdmitRepository Port
 *
 * DDD: Application port for admitrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AdmitAlertToQueueInput, AdmitAlertToQueueOutput } from "../dto/admit.dto";
export interface AdmitRepository {
  admitAlertToQueue(input: AdmitAlertToQueueInput): Promise<AdmitAlertToQueueOutput>;
}

export type { AdmitAlertToQueueInput, AdmitAlertToQueueOutput } from "../dto/admit.dto";
