/**
 * ContainmentActionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContainmentActionRepository Port
 *
 * DDD: Application port for containmentactionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExecuteContainmentActionInput, ExecuteContainmentActionOutput } from "../dto/containment-action.dto";
export interface ContainmentActionRepository {
  executeContainmentAction(input: ExecuteContainmentActionInput): Promise<ExecuteContainmentActionOutput>;
}

export type { ExecuteContainmentActionInput, ExecuteContainmentActionOutput } from "../dto/containment-action.dto";
