/**
 * QueueRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QueueRepository Port
 *
 * DDD: Application port for queuerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListTriageQueueInput, ListTriageQueueOutput } from "../dto/queue.dto";
export interface QueueRepository {
  listTriageQueue(input: ListTriageQueueInput): Promise<ListTriageQueueOutput>;
}

export type { ListTriageQueueInput, ListTriageQueueOutput } from "../dto/queue.dto";
