/**
 * ShiftRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShiftRepository Port
 *
 * DDD: Application port for shiftrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListTriageShiftsInput, ListTriageShiftsOutput, OpenTriageShiftInput, OpenTriageShiftOutput } from "../dto/shift.dto";
export interface ShiftRepository {
  listTriageShifts(input: ListTriageShiftsInput): Promise<ListTriageShiftsOutput>;
  openTriageShift(input: OpenTriageShiftInput): Promise<OpenTriageShiftOutput>;
}

export type { ListTriageShiftsInput, ListTriageShiftsOutput, OpenTriageShiftInput, OpenTriageShiftOutput } from "../dto/shift.dto";
