/**
 * ListKri DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListKeyRiskIndicatorsParams } from "@alertworth/core/indicators";

export function createListKriRequest(overrides: Partial<ListKeyRiskIndicatorsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
