/**
 * Routes for Refresh
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: indicators
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { refreshKeyRiskIndicator } from "../handlers/refresh.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function refreshRoutes(fastify: FastifyInstance) {
  // POST /v1/kris/{kriId}/refresh (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/kris/:kriId/refresh",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { kriId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getIndicatorsDependenciesForRequest();
        await refreshKeyRiskIndicator(request, reply, deps);
      });
    }
  );


}
