/**
 * AdmitRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdmitRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AdmitRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AdmitRepository,
} from "@alertworth/services/triage";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AdmitRepositoryDdb } from "./admit-repository.ddb.js";

/**
 * AdmitRepositoryAdapter
 *
 * Implements AdmitRepository port for infrastructure layer.
 */
export class AdmitRepositoryAdapter implements AdmitRepository {
  private readonly ddb: AdmitRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AdmitRepositoryDdb(this.dynamoClient);
  }

  async admitAlertToQueue(input: Parameters<AdmitRepository['admitAlertToQueue']>[0]): Promise<Awaited<ReturnType<AdmitRepository['admitAlertToQueue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.admitAlertToQueue(input);
  }
}
