/**
 * ContainmentActionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContainmentActionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ContainmentActionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ContainmentActionRepository,
} from "@alertworth/services/triage";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ContainmentActionRepositoryDdb } from "./containment-action-repository.ddb.js";

/**
 * ContainmentActionRepositoryAdapter
 *
 * Implements ContainmentActionRepository port for infrastructure layer.
 */
export class ContainmentActionRepositoryAdapter implements ContainmentActionRepository {
  private readonly ddb: ContainmentActionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ContainmentActionRepositoryDdb(this.dynamoClient);
  }

  async executeContainmentAction(input: Parameters<ContainmentActionRepository['executeContainmentAction']>[0]): Promise<Awaited<ReturnType<ContainmentActionRepository['executeContainmentAction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.executeContainmentAction(input);
  }
}
