/**
 * QueueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QueueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements QueueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  QueueRepository,
} from "@alertworth/services/triage";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { QueueRepositoryDdb } from "./queue-repository.ddb.js";

/**
 * QueueRepositoryAdapter
 *
 * Implements QueueRepository port for infrastructure layer.
 */
export class QueueRepositoryAdapter implements QueueRepository {
  private readonly ddb: QueueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new QueueRepositoryDdb(this.dynamoClient);
  }

  async listTriageQueue(input: Parameters<QueueRepository['listTriageQueue']>[0]): Promise<Awaited<ReturnType<QueueRepository['listTriageQueue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTriageQueue(input);
  }
}
