/**
 * ShiftRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShiftRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ShiftRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ShiftRepository,
} from "@alertworth/services/triage";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ShiftRepositoryDdb } from "./shift-repository.ddb.js";

/**
 * ShiftRepositoryAdapter
 *
 * Implements ShiftRepository port for infrastructure layer.
 */
export class ShiftRepositoryAdapter implements ShiftRepository {
  private readonly ddb: ShiftRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ShiftRepositoryDdb(this.dynamoClient);
  }

  async listTriageShifts(input: Parameters<ShiftRepository['listTriageShifts']>[0]): Promise<Awaited<ReturnType<ShiftRepository['listTriageShifts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTriageShifts(input);
  }

  async openTriageShift(input: Parameters<ShiftRepository['openTriageShift']>[0]): Promise<Awaited<ReturnType<ShiftRepository['openTriageShift']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openTriageShift(input);
  }
}
