/**
 * ContainmentAction Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ContainmentActionEntity } from "@alertworth/core/triage/models/index.js";
import { triageSchemas } from "@alertworth/core/triage";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "trg";

export function createContainmentAction(overrides: Partial<ContainmentActionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `act_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    actionType: overrides.actionType ?? "isolate_host",
    alertId: overrides.alertId ?? `alt_${ulid().toLowerCase()}`,
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return triageSchemas.ContainmentAction.parse(raw);
}

export function containmentActionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createContainmentAction(overrides));
}
